<a href="https://colab.research.google.com/github/ankitakalli3232-prog/ML122/blob/main/ankita.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [6]:
import numpy as np
np.array(my_list)

array([1, 2, 3])

In [8]:
my_matrix = [[1,2,3] , [4,5,6] , [7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [17]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(5,5)

array([[0.1809435 , 0.70435718, 0.07013333, 0.04601869, 0.733506  ],
       [0.49553074, 0.04435198, 0.73075035, 0.92865789, 0.55357398],
       [0.95268395, 0.64029602, 0.56546476, 0.28342071, 0.15067778],
       [0.50277213, 0.40751519, 0.71025348, 0.10234803, 0.08803059],
       [0.12855188, 0.79361582, 0.40685113, 0.09133089, 0.72889391]])

In [20]:
np.random.randn(2)

array([0.39270763, 0.17191703])

In [21]:
np.random.randn(5,5)

array([[-0.5650497 , -1.0494133 , -1.43341456, -0.98914481, -0.95419392],
       [-0.3528388 ,  0.33058208,  0.15508223, -0.56264479,  0.25459239],
       [-0.06690565, -0.82433385, -0.51748809, -0.72099857,  0.71887998],
       [ 0.88902174,  0.77397301,  0.33378419,  0.15459605, -0.25132215],
       [ 0.88649847, -0.15571067,  0.68523085,  1.2185629 , -0.14762531]])

In [22]:
np.random.randint(1,100)

5

In [23]:
np.random.randint(1,100,10)

array([59, 21, 42, 81,  6,  2, 83, 78, 10, 65])

In [25]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr

array([ 7, 19, 38,  4,  0, 46, 33, 24, 40, 29])